<?require("{$_SERVER["DOCUMENT_ROOT"]}/bitrix/header.php");

use Lang\Main\Css\Generate;


$cssStyleProeprty = [
	'display' => [
	  'inherit' => '',
	  'inline' => '',
	  'block' => '',
	  'flex' => '',
	  'inline-block' => '',
	  'inline-flex' => '',
	  'inline-table' => '',
	  'list-item' => '',
	  'table' => '',
	  'table-caption' => '',
	  'table-column' => '',
	  'table-column-group' => '',
	  'table-cell' => '',
	  'table-header-group' => '',
	  'table-footer-group' => '',
	  'table-row-group' => '',
	  'table-row' => '',
	  'none' => '',
	],
    'width' => [
        'auto' => '',
        'inherit' => '',
        0 => '',
    ],
	'max-width' => [
        'inherit' => '',
        'none' => '',
    ],
	'min-width' => [
        'inherit' => '',
        'none' => '',
    ],
	'height' => [
	  'auto' => '',
	  'inherit	' => '',
	  0 => '',
	],
	'max-height' => [
        'inherit' => '',
        'none' => '',
    ],
	'min-height' => [
        'inherit' => '',
        'none' => '',
    ],
	'margin' => [
        'auto' => '',
        'inherit' => '',
        '0' => '',
    ],
    'margin-top' => [
        'auto' => '',
        'inherit' => '',
        '0' => '',
    ],
	'margin-right' => [
        'auto' => '',
        'inherit' => '',
        '0' => '',
    ],
	'margin-bottom' => [
        'auto' => '',
        'inherit' => '',
        '0' => '',
    ],
	'margin-left' => [
        'auto' => '',
        'inherit' => '',
        '0' => '',
    ],
	'padding' => [
        'inherit' => '',
        '0' => '',
    ],
    'padding-top' => [
        'inherit' => '',
        '0' => '',
    ],
    'padding-right' => [
        'inherit' => '',
        '0' => '',
    ],
	'padding-bottom' => [
        'inherit' => '',
        '0' => '',
    ],
	'padding-left' => [
        'inherit' => '',
        '0' => '',
    ],
	'position' => [],
	'bottom' => [],
	'left' => [],
	'right' => [],
	'top' => [],
	'z-index' => [],
	'overflow' => [],
	'overflow-x' => [],
	'overflow-y' => [],
	'opacity' => [],
	'border' => [],
	'border-width' => [],
	'border-style' => [],
	'border-color' => [],
	'border-bottom' => [],
	'border-bottom-width' => [],
	'border-bottom-style' => [],
	'border-bottom-color' => [],
	'border-left' => [],
	'border-left-width' => [],
	'border-left-style' => [],
	'border-left-color' => [],
	'border-top' => [],
	'border-top-width' => [],
	'border-top-style' => [],
	'border-top-color' => [],
	'border-right' => [],
	'border-right-width' => [],
	'border-right-style' => [],
	'border-right-color' => [],
	'border-radius' => [],
	'border-top-left-radius' => [],
	'border-top-right-radius' => [],
	'border-bottom-left-radius' => [],
	'border-bottom-right-radius' => [],
	'background' => [],
	'background-color' => [],
	'background-image' => [],
	'background-position' => [],
	'background-repeat' => [],
	'background-size' => [],
	'background-attachment' => [],
	'background-clip' => [],
	'background-origin' => [],
	'background-blend-mode' => [],
	'flex' => [],
	'flex-basis' => [],
	'flex-grow' => [],
	'flex-shrink' => [],
	'flex-flow' => [],
	'flex-direction' => [],
	'flex-wrap' => [],
	'align-content' => [],
	'align-items' => [],
	'align-self' => [],
	'order' => [],
	'justify-content' => [],
	'gap' => [],
	'grid' => [],
	'grid-area' => [],
	'grid-auto-columns' => [],
	'grid-auto-flow' => [],
	'grid-auto-rows' => [],
	'grid-column' => [],
	'grid-column-end' => [],
	'grid-column-start' => [],
	'grid-row' => [],
	'grid-row-end' => [],
	'row-gap' => [],
	'grid-row-start' => [],
	'grid-template' => [],
	'grid-template-areas' => [],
	'grid-template-columns' => [],
	'grid-template-rows' => [],
	'outline' => [],
	'outline-color' => [],
	'outline-offset' => [],
	'outline-style' => [],
	'outline-width' => [],
	'cursor' => [],
	'caret-color' => [],
	'transition' => [],
	'transition-delay' => [],
	'transition-duration' => [],
	'transition-property' => [],
	'transition-timing-function' => [],
	'box-shadow' => [],
	'transform' => [],
	'transform-origin' => [],
	'transform-style' => [],
	'animation' => [],
	'animation-name' => [],
	'animation-duration' => [],
	'animation-delay' => [],
	'animation-direction' => [],
	'animation-fill-mode' => [],
	'animation-iteration-count' => [],
	'animation-play-state' => [],
	'animation-timing-function' => [],
	'text-transform' => [
	  'inherit' => '',
	  'lowercase' => '',
	  'uppercase' => '',
	  'capitalize' => '',
	  'none' => '',
	],
	'white-space' => [
	  'normal' => '',
	  'nowrap' => '',
	  'pre' => '',
	  'pre-wrap' => '',
	  'pre-line' => '',
	  'break-spaces' => '',
	  'inherit' => '',
	],
	'tab-size' => [
	  8 => '',
	  0 => '',
	  'inherit' => '',
	],
	'word-break' => [
	  'normal' => '',
	  'break-all' => '',
	  'keep-all' => '',
	  'inherit' => '',
	],
	'line-break' => [
	  'auto' => '',
	  'loose' => '',
	  'normal' => '',
	  'strict' => '',
	  'inherit' => '',
	],
	'hyphens' => [
	  'manual' => '',
	  'auto' => '',
	  'inherit' => '',
	  'none' => '',
	],
	'overflow-wrap' => [
	  'normal' => '',
	  'break-word' => '',
	  'anywhere' => '',
	  'inherit' => '',
	],
	'word-wrap' => [
	  'normal' => '',
	  'break-word' => '',
	  'anywhere' => '',
	  'inherit' => '',
	],
	'text-align' => [
	  'start' => '',
	  'end' => '',
	  'left' => '',
	  'right' => '',
	  'center' => '',
	  'justify' => '',
	  'justify-all' => '',
	  'match-parent' => '',
	  'inherit' => '',
	],
	'text-align-all' => [],
	'text-align-last' => [],
	'word-spacing' => [],
	'letter-spacing' => [],
	'text-indent' => [],
	'text-decoration-line' => [],
	'text-decoration-style' => [],
	'text-decoration-color' => [],
	'text-decoration' => [],
	'text-underline-position' => [],
	'text-shadow' => [],
	'font-family' => [],
	'font-weight' => [],
	'font-stretch' => [],
	'font-style' => [],
	'font-size' => [],
	'font-size-adjust' => [],
	'font-synthesis' => [],
	'font-feature-settings' => [],
	'font-kerning' => [],
	'font-variant' => [],
	'font-variant-caps' => [],
	'font-variant-east-asian' => [],
	'font-variant-ligatures' => [],
	'font-variant-numeric' => [],
	'font-variant-position' => [],
	'border-collapse' => [],
	'border-spacing' => [],
	'caption-side' => [],
	'empty-cells' => [],
	'table-layout' => [],
	'list-style' => [],
	'list-style-type' => [],
	'list-style-image' => [],
	'list-style-position' => [],
	'box-sizing' => [
        'content-box' => '',
        'border-box' => '',
        'inherit' => '',
    ],
	'vertical-align' => [
        'baseline' => '',
        'sub' => '',
        'super' => '',
        'top' => '',
        'text-top' => '',
        'middle' => '',
        'bottom' => '',
        'text-bottom' => '',
        'inherit' => '',
    ],
	'line-height' => [
        'normal' => '',
        'inherit' => '',
        '1' => '',
    ],
	'float' => [],
	'clear' => [],
	'object-fit' => [],
	'object-position' => [],
	'text-overflow' => [],
	'visibility' => [],
	'border-image' => [],
	'border-image-outset' => [],
	'border-image-repeat' => [],
	'border-image-slice' => [],
	'border-image-source' => [],
	'border-image-width' => [],
	'content' => [],
	'counter-increment' => [],
	'counter-reset' => [],
	'quotes' => [],
	'backface-visibility' => [],
	'perspective' => [],
	'perspective-origin' => [],
	'column-rule' => [],
	'column-rule-width' => [],
	'column-rule-style' => [],
	'column-rule-color' => [],
	'columns' => [],
	'column-count' => [],
	'column-width' => [],
	'column-gap' => [],
	'column-span' => [],
	'column-fill' => [],
	'page-break-after' => [],
	'page-break-before' => [],
	'page-break-inside' => [],
	'resize' => [],
	'mix-blend-mode' => [],
	'isolation' => [],
	'break-before' => [],
	'break-aftere' => [],
	'break-inside' => [],
	'box-decoration-break' => [],
	'orphans' => [],
	'widows' => [],
	'accent-color' => [],
	'align-tracks' => [],
	'all' => [],
	'animation-timeline' => [],
	'appearance' => [],
	'aspect-ratio' => [],
	'backdrop-filter' => [],
	'background-position-x' => [],
	'background-position-y' => [],
	'block-size' => [],
	'border-block' => [],
	'border-block-color' => [],
	'border-block-end' => [],
	'border-block-end-color' => [],
	'border-block-end-style' => [],
	'border-block-end-width' => [],
	'border-block-start' => [],
	'border-block-start-color' => [],
	'border-block-start-style' => [],
	'border-block-start-width' => [],
	'border-block-style' => [],
	'border-block-width' => [],
	'border-end-end-radius' => [],
	'border-end-start-radius' => [],
	'border-inline' => [],
	'border-inline-color' => [],
	'border-inline-end' => [],
	'border-inline-end-color' => [],
	'border-inline-end-style' => [],
	'border-inline-end-width' => [],
	'border-inline-start' => [],
	'border-inline-start-color' => [],
	'border-inline-start-style' => [],
	'border-inline-start-width' => [],
	'border-inline-style' => [],
	'border-inline-width' => [],
	'border-start-end-radius' => [],
	'border-start-start-radius' => [],
	'break-after' => [],
	'clip-path' => [],
	'clip-rule' => [],
	'color' => [],
	'color-interpolation-filters' => [],
	'color-scheme' => [],
	'contain' => [],
	'content-visibility' => [],
	'counter-set' => [],
	'cue' => [],
	'cue-after' => [],
	'cue-before' => [],
	'direction' => [],
	'filter' => [],
	'flood-color' => [],
	'flood-opacity' => [],
	'font' => [],
	'font-language-override' => [],
	'font-optical-sizing' => [],
	'font-variant-alternates' => [],
	'font-variation-settings' => [],
	'forced-color-adjust' => [],
	'globalcompositeoperation' => [],
	'glyph-orientation-vertical' => [],
	'grid-column-gap' => [],
	'grid-gap' => [],
	'grid-row-gap' => [],
	'hanging-punctuation' => [],
	'hyphenate-character' => [],
	'image-orientation' => [],
	'image-rendering' => [],
	'image-resolution' => [],
	'inherit' => [],
	'initial' => [],
	'initial-letter' => [],
	'initial-letter-align' => [],
	'initial-value' => [],
	'inline-size' => [],
	'inset' => [],
	'inset-block' => [],
	'inset-block-end' => [],
	'inset-block-start' => [],
	'inset-inline' => [],
	'inset-inline-end' => [],
	'inset-inline-start' => [],
	'justify-items' => [],
	'justify-self' => [],
	'justify-tracks' => [],
	'lighting-color' => [],
	'line-height-step' => [],
	'margin-block' => [],
	'margin-block-start' => [],
	'margin-inline' => [],
	'margin-inline-end' => [],
	'margin-inline-start' => [],
	'margin-trim' => [],
	'mask' => [],
	'mask-border' => [],
	'mask-border-mode' => [],
	'mask-border-outset' => [],
	'mask-border-repeat' => [],
	'mask-border-slice' => [],
	'mask-border-source' => [],
	'mask-border-width' => [],
	'mask-clip' => [],
	'mask-composite' => [],
	'mask-image' => [],
	'mask-mode' => [],
	'mask-origin' => [],
	'mask-position' => [],
	'mask-repeat' => [],
	'mask-size' => [],
	'mask-type' => [],
	'masonry-auto-flow' => [],
	'math-style' => [],
	'max-block-size' => [],
	'max-inline-size' => [],
	'max-zoom' => [],
	'min-block-size' => [],
	'min-inline-size' => [],
	'min-zoom' => [],
	'offset' => [],
	'offset-anchor' => [],
	'offset-distance' => [],
	'offset-path' => [],
	'offset-position' => [],
	'offset-rotate' => [],
	'overflow-anchor' => [],
	'overflow-block' => [],
	'overflow-clip-margin' => [],
	'overflow-inline' => [],
	'overscroll-behavior' => [],
	'overscroll-behavior-block' => [],
	'overscroll-behavior-inline' => [],
	'overscroll-behavior-x' => [],
	'overscroll-behavior-y' => [],
	'padding-block' => [],
	'padding-block-end' => [],
	'padding-block-start' => [],
	'padding-inline' => [],
	'padding-inline-end' => [],
	'padding-inline-start' => [],
	'paint-order' => [],
	'pause' => [],
	'pause-after' => [],
	'pause-before' => [],
	'pitch' => [],
	'pitch-range' => [],
	'place-content' => [],
	'place-items' => [],
	'place-self' => [],
	'play-during' => [],
	'pointer-events' => [],
	'print-color-adjust' => [],
	'rest' => [],
	'rest-after' => [],
	'rest-before' => [],
	'richness' => [],
	'ruby-align' => [],
	'ruby-position' => [],
	'scale' => [],
	'scroll-behavior' => [],
	'scroll-margin' => [],
	'scroll-margin-block' => [],
	'scroll-margin-block-end' => [],
	'scroll-margin-block-start' => [],
	'scroll-margin-bottom' => [],
	'scroll-margin-inline' => [],
	'scroll-margin-inline-end' => [],
	'scroll-margin-inline-start' => [],
	'scroll-margin-left' => [],
	'scroll-margin-right' => [],
	'scroll-margin-top' => [],
	'scroll-padding' => [],
	'scroll-padding-block' => [],
	'scroll-padding-block-end' => [],
	'scroll-padding-block-start' => [],
	'scroll-padding-bottom' => [],
	'scroll-padding-inline' => [],
	'scroll-padding-inline-end' => [],
	'scroll-padding-inline-start' => [],
	'scroll-padding-left' => [],
	'scroll-padding-right' => [],
	'scroll-padding-top' => [],
	'scroll-snap-align' => [],
	'scroll-snap-stop' => [],
	'scroll-snap-type' => [],
	'scrollbar-color' => [],
	'scrollbar-gutter' => [],
	'scrollbar-width' => [],
	'shape-image-threshold' => [],
	'shape-margin' => [],
	'shape-outside' => [],
	'speak' => [],
	'speak-as' => [],
	'speak-header' => [],
	'speak-numeral' => [],
	'speak-punctuation' => [],
	'speech-rate' => [],
	'stress' => [],
	'text-combine-upright' => [],
	'text-decoration-skip' => [],
	'text-decoration-skip-ink' => [],
	'text-decoration-thickness' => [],
	'text-emphasis' => [],
	'text-emphasis-color' => [],
	'text-emphasis-position' => [],
	'text-emphasis-style' => [],
	'text-justify' => [],
	'text-orientation' => [],
	'text-rendering' => [],
	'text-underline-offset' => [],
	'touch-action' => [],
	'transform-box' => [],
	'unicode-bidi' => [],
	'unset' => [],
	'user-select' => [],
	'voice-balance' => [],
	'voice-duration' => [],
	'voice-family' => [],
	'voice-pitch' => [],
	'voice-range' => [],
	'voice-rate' => [],
	'voice-stress' => [],
	'voice-volume' => [],
	'volume' => [],
	'will-change' => [],
	'writing-mode' => [],
];
  
  $gM = new Generate($cssStyleProeprty);
  
  
  echo '<pre>';
  echo 'Конечный массив ' . count($gM->modifierEnd) . ' - ' . count($cssStyleProeprty) . ' Конечный массив<br><br>';
  print_r($gM->modifierEnd);
  echo '</pre>';
  
  echo '<pre>';
  print_r($gM->modifierDouble);
  echo '</pre>';
  
  // if()
  // {
	// foreach($cssStyleProeprty as $k => $v)
	// {
	//   echo 'Конечный массив ' . count($gM->modifierEnd) . ' - ' . count($cssStyleProeprty) . ' Конечный массив<br><br>';
	// }
  // }
  
  $pseudoClasses = [
	'::placeholder' => [
	  '' => '',
	],
	':checked' => [
	  '' => '',
	],
	':disabled' => [
	  '' => '',
	],
	':enabled' => [
	  '' => '',
	],
	':indeterminate' => [
	  '' => '',
	],
	':in-range' => [
	  '' => '',
	],
	':invalid' => [
	  '' => '',
	],
	':optional' => [
	  '' => '',
	],
	':out-of-range' => [
	  '' => '',
	],
	':read-only' => [
	  '' => '',
	],
	':required' => [
	  '' => '',
	],
	':valid' => [
	  '' => '',
	],
	':nth-child()' => [
	  '' => '',
	],
	':first-child' => [
	  '' => '',
	],
	':last-child' => [
	  '' => '',
	],
	':nth-last-child()' => [
	  '' => '',
	],
	':only-child' => [
	  '' => '',
	],
	':nth-of-type()' => [
	  '' => '',
	],
	':nth-last-of-type()' => [
	  '' => '',
	],
	':first-of-type' => [
	  '' => '',
	],
	':last-of-type' => [
	  '' => '',
	],
	':only-of-type' => [
	  '' => '',
	],
	':link' => [
	  '' => '',
	],
	':visited' => [
	  '' => '',
	],
	':hover' => [
	  '' => '',
	],
	':active' => [
	  '' => '',
	],
	':focus' => [
	  '' => '',
	],
	':target' => [
	  '' => '',
	],
	':lang()' => [
	  '' => '',
	],
	':not()' => [
	  '' => '',
	],
	':empty' => [
	  '' => '',
	],
	':root' => [
	  '' => '',
	],
	':after' => [
	  '' => '',
	],
	':before' => [
	  '' => '',
	],
	':first-letter' => [
	  '' => '',
	],
	':first-line' => [
	  '' => '',
	],
	'::selection' => [
	  '' => '',
	],
  ];

?>

<?require("{$_SERVER["DOCUMENT_ROOT"]}/bitrix/footer.php");?>